### ISSUE TITLE
Error : No compatible version found

### ISSUE THREAD

**Issue by jaleedriaz** [andrew/node-gps#3]
Hi there !!!

I found an error when trying to install gps. However, I did exactly what you recommend :

> npm install gps

see my screenshot :

![gps_error](https://f.cloud.github.com/assets/6131571/1698999/0c8dc030-5f77-11e3-97d2-cf72291791c3.png)

If you have any idea then please help me
Thanks :)
(PS : I am from france so forgive me for my english :P)

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
